
---
title: "Problem Set 3 - Instrumental Variables"
author: 
- name: Melyssa Pina Sigg
- name: Luca Keiser

date: "16 April 2021"
output:
  html_document:
    highlight: tango
    theme: cosmo
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: false
    df_print: paged
---

```{r, include=FALSE}
# Keep this setup code chunk also in your problem set.
# Also, use this line to load the packages that are needed
library(tidyverse)
library(kableExtra)
library(wooldridge)
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning = FALSE)
```


# Learning goals

- Understanding the set up of IV studies
- Apply IV regression in practice
- Practicing data analysis


## Exercise 1

Use Google Scholar to find three examples of instrumental variables in published scientific research (in any area). List the three instruments describing (1-2 lines) the outcome variable, the endogenous treatment, and how the instrument solves the issue.

#Deniz Güvercin (2019): Women in Politics and Child Labor: an Instrumental Variable Approach
#Research question = How increasing the participation of women in government-level decisions decreases child labor?
#Instrument variable (z) = quotas * gender index (i.e., gender electoral quota interacted with an index displaying the intensity of gender marking in language)
#Treatment variable (d) = female seat share (i.e., share of parliamentary seats held by women)
#Outcome variable (y) = child labor (i.e., percentage of children aged 5 to 14 years involved in child labor activities)
#The instrumental variable approach is used to avoid endogeneity issues because of omitted variable bias that would generate biased coefficients, leading to nonidentification of the correct impact of the main variable of interest (female seat share) on the dependent variable (child labor). Therefore, using an instrumental variable approach enables to overcome any potential biased coefficients produced by OLS regression (to leverage partially exogenous treatment variation in observational studies).
#CRITIC: the IV approach in this study does not satisfy one of the three requirements: Z is random or "as if" random [a.k.a. independence assumption.

#Muntasir Murshed (2019): Are Trade Liberalization policies aligned with Renewable Energy Transition in low and middle income countries? An Instrumental Variable approach
#Instrument variables (z) = Real Exchange Rate, Terms of Trade, Tariffs levied on imports
#Treatment variable (d) = Trade Liberalization (i.e., trade openness: total volume of imports and exports)
#Outcome variable (y) = RET (i.e., four indicators of RET: renewable energy consumption, renewable energy share, intensity of renewable energy use, access to clean fuel and technology for cooking)
#The instrumental variable approach is used to modify the problematic endogenous regressor/s being correlated with the error term.
#CRITIC: the IV approach in this study does not satisfy one of the three requirements: Z is random or "as if" random [a.k.a. independence assumption].

#Daniel Kim, Christopher F Baum, Michael Ganz, S V Subramanian, and Ichiro Kawachi (2011): The contextual effects of social capital on health: a cross national instrumental variable analysis
#Instrument variables (z) = Corruption, Higher population densities, Religious fractionalization 
#Treatment variable (d) = Social trust
#Outcome variable (y) = Individual self-rated health
#The instrumental variable approach is used to modify the problematic endogenous regressor/s being correlated with the error term.


## Exercise 2 (no coding)

Install the package `wooldridge` and lead the data `bwght` (you can get help with `?bwght` after loading the package). Use the data study the causal effect of smoking mothers on the weight of the babies. 

First think:   
1. What would be the ideal experiment to identify the relationship between maternal smoking and the weight of the baby? What would be the problem with that?  
2. Can you think of a good instrument for smoking cigarettes? Better if the instrument... is not in the data! :)  
3. Describe the three requirement with respect to your instrument.

#1. The ideal experiment would be to use an instrumental variable (IV) approach because we cannot run an experiment for ethical reasons in this case.

#2. Instrumental variable: Anti-Smoking Campaign 

#3. Three requirements:
#Z has a causal effect on the endogenous treatment D: Kenneth Warner (1977) found that anti-smoking campaign has a causal effect on cigarette consumption. It could be that anti-smoking campaign have an effect on mothers’ cigarette consumption.
#Z is random because we can randomly expose one group to the treatment “anti-smoking campaign” and the other group does not get the treatment.
#Z affects Y only though D: it should be the case because it should not be possible that one “anti-smoking campaign” affects the weight of babies.


## Exercise 3
Find the variables for the number of cigarettes smoked during pregnancy and the weight of the babies (which is an indicator of overall health of newborn babies). 

### 3.1
Start by exploring the naive correlation between the number of cigarettes smoked per day during pregnancy on the birth weight in ounces: use the two variables to estimate a naive OLS regression model that predicts the weight of babies with the number of cigarettes smoked by the mother during the pregnancy. What do you find? is this an estimate of the causal effect of smoking? Why? Finally, choose from the variable list two potential omitted variables and add them to a second model. Is the estimate changing? Is this a causal effect now?

### 3.2
Check out the data and find a viable **instrument** for smoking. 
Defend the three requirements of the instrument.

### 3.3
Now manually compute the two stages of the 2SLS strategy (i.e., first stage, predict, and then use predicted values in the outcome equation).

### 3.4
Finally, estimate a 2SLS in one go calling the function `AER::ivreg()`. Self-learn how to use it. 

### 3.5 
Build a regression table with three models:  
1. `Naive OLS` with the simple naive regression of baby weights on cigarettes smoked;  
2. `IV manual` with the result from the two stages estimated manually (show only outcome equation);  
3. `IV-2SLS` with the result from `ivreg()`. 

Comment. 

## Exercise 4 

Skim through the paper by Acemoglu, Johnson, and Robinson (2001) [[link](https://www.aeaweb.org/articles?id=10.1257/aer.91.5.1369)]. Describe their research question, the source of endogeneity, and the instrumental variable that they use. (max 4 lines) Then, use the replication data stored [here](https://www.openicpsr.org/openicpsr/project/112564/version/V1/view?path=/openicpsr/112564/fcr:versions/V1/Acemoglu-Johnson-and-Robinson-datafiles&type=folder) to replicate Figure 1, Figure 3, and Table 4 (panel A only, p. 1386). 

**Warning**. You must work collaboratively using GitHub. Please create the repo at the class organization (not at your personal account). All the tips from PS1 still apply (plan the work, use issues, branches, pull requests...). 

